<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-BKCB67H0" failures="5" tests="5" name="com.api.myRunner.TestRunner" time="9.830" errors="0" timestamp="12 May 2022 06:16:12 GMT" skipped="0">
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="3.948">
    <failure message="398481Is not matching with io.restassured.path.xml.XmlPath@47c26664 expected [398481] but found [io.restassured.path.xml.XmlPath@7f74fefa]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398481Is not matching with io.restassured.path.xml.XmlPath@47c26664 expected [398481] but found [io.restassured.path.xml.XmlPath@7f74fefa]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398481"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.403">
    <failure message="398485Is not matching with io.restassured.path.xml.XmlPath@697913e6 expected [398485] but found [io.restassured.path.xml.XmlPath@58a60d56]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398485Is not matching with io.restassured.path.xml.XmlPath@697913e6 expected [398485] but found [io.restassured.path.xml.XmlPath@58a60d56]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398485"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.525">
    <failure message="398482Is not matching with io.restassured.path.xml.XmlPath@440e3972 expected [398482] but found [io.restassured.path.xml.XmlPath@ef77972]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398482Is not matching with io.restassured.path.xml.XmlPath@440e3972 expected [398482] but found [io.restassured.path.xml.XmlPath@ef77972]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398482"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.520">
    <failure message="398484Is not matching with io.restassured.path.xml.XmlPath@72f628d6 expected [398484] but found [io.restassured.path.xml.XmlPath@1e8d4d07]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398484Is not matching with io.restassured.path.xml.XmlPath@72f628d6 expected [398484] but found [io.restassured.path.xml.XmlPath@1e8d4d07]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398484"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.434">
    <failure message="398483Is not matching with io.restassured.path.xml.XmlPath@489fa87e expected [398483] but found [io.restassured.path.xml.XmlPath@19048fda]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398483Is not matching with io.restassured.path.xml.XmlPath@489fa87e expected [398483] but found [io.restassured.path.xml.XmlPath@19048fda]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398483"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- com.api.myRunner.TestRunner -->
