<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-BKCB67H0" failures="4" tests="5" name="com.api.myRunner.TestRunner" time="16.049" errors="0" timestamp="12 May 2022 11:47:30 GMT" skipped="0">
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="4.043"/>
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="2.292">
    <failure message="398482Is not matching with 398481 expected [398482] but found [398481]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398482Is not matching with 398481 expected [398482] but found [398481]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:60)
at ✽.verify NaceDetails are as per "398482"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="7.093">
    <failure message="398483Is not matching with 398481 expected [398483] but found [398481]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398483Is not matching with 398481 expected [398483] but found [398481]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:60)
at ✽.verify NaceDetails are as per "398483"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.255">
    <failure message="398485Is not matching with 398481 expected [398485] but found [398481]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398485Is not matching with 398481 expected [398485] but found [398481]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:60)
at ✽.verify NaceDetails are as per "398485"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="com.api.myRunner.TestRunner" name="feature" time="1.366">
    <failure message="398484Is not matching with 398481 expected [398484] but found [398481]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 398484Is not matching with 398481 expected [398484] but found [398481]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:60)
at ✽.verify NaceDetails are as per "398484"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- com.api.myRunner.TestRunner -->
